### ISSUE TITLE
Refactor model to cater to richer display of non-primitive data types

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-models#12]
With the introduction of subject and location concept data types, there is need to update the model to allow for richer display of these data types on the clients.

**Tech tasks**:
- **Model**: Introduce a Displayable type which includes both the text to be displayed as well as a backing entity object that can be accessed by the respective clients to generate the richer display.
- **Model**: Add plumbing in order to fetch the backing entity objects as required based on the data type.
- **Server**: Update Server to return the required entity objects against observations.
- **DEA**: Update Data Entry App to use the new displayable class
- **Android Client**: Update Android client to use the new displayable type.

**Acceptance criteria**:
All observations in Registration, Enrolment, Encounter, Program encounter should continue to be shown as before. Observations with concepts data type Subject will be linked to the particular subject.

**Comment by 1t5j0y** [comment]
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-5e0a7-2020-10-28-14-25-58.apk

**Comment by hithacker** [comment]
Test scenarios:

- [ ] Test with one of the implementations with old rules and decisions and inheriting from 1.
- [ ] Test with one of the implementations with new rules and decisions
- [ ] Test all type of concepts
