### ISSUE TITLE
Unable to get affiliatedGroups for Individual 

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-models#48]
## Background info
In Jss Phulwari programs, "Child enrolment" form, .. 
 - We determine the Phulwari to be associated based on village name
 - AffiliationGroups are set for the Individual using the GroupAffiliation FormElement
 - in the EnrolmentId FormElement, we have a rule that fetches the affiliatedGroups. It then uses the villageName, PhulwariName(extracted from  affiliatedGroups) and GeneratedID (From IdSource) to come up with final Enrolment ID. 

## Issue

During EnrolmentId FormElement rule execution, we fail to fetch affiliatedGroups, resulting in "Enrolment ID" not being set.

## Rule snippet
```
const phulwariName = _.get(_.find(programEnrolment.individual.affiliatedGroups, ({voided}) => !voided), ['groupSubject', 'firstName'], '');
```

## Root Cause
After ReactNative upgrade, we are not able to access temp property affiliatedGroups in Individual from enrolment during ProgramEnrolment Create / edit. This is due to the fact that, individual returned for enrolment.individual is the realmDb object, which is fetched fresh from db.

Therefore the rule fails to fetch affiliatedGroups on individual of an enrolment, and therefore "Enrolment ID" generation fails.

## Possible fix
~We cannot convert temp property affiliatedGroups to persistent value of individual, as the individual does not get saved duing enrolment form filling. Therefore the only solution is to switch to using Enrolment to store the temp property affiliatedGroups and modify the Rules suitably. This has already been tested to work in dev environment.~

## Final solution after pairing with Vinay
 - We do not like the approach of using temporary variables for storing the affiliatedGroups information. All such details should be passed to the ruleEvaluationService as part of the entityContext object. 

 - Also, in the Subject/ Person summary view, pass the required affiliatedGroups separately from state during invocation and dont expect it to be a temp variable in Individual.

# Post release steps
After the release, Support team would need to modify [all rules](https://github.com/avniproject/avni-models/issues/48#issuecomment-1674200507) that refer to "individual.affiliatedGroups" to instead use "params.entityContext.affiliatedGroups".

## Old Rule snippet
```
const phulwariName = _.get(_.find(programEnrolment.individual.affiliatedGroups, ({voided}) => !voided), ['groupSubject', 'firstName'], '');
```

## New Rule snippet
```
const phulwariName = _.get(_.find(params.entityContext.affiliatedGroups, ({voided}) => !voided), ['groupSubject', 'firstName'], '');
```

##Support ticket
https://avni.freshdesk.com/a/tickets/2925

**Comment by himeshr** [comment]
This code change would require change in rules for following FormElements across multiple organisations:

select o.name, form_element.name
from form_element
join organisation o on form_element.organisation_id = o.id
where rule like '%nrolment.individual.affiliatedGroups%';

#|name|name
-|------|-------
1|JSSCP UAT|Enrolment ID
2|JSS Singrauli UAT|Enrolment ID
3|JSSCP|Enrolment ID
4|JSS|Enrolment ID
5|JSSCP Support|Enrolment ID
6|Achala Test|Enrolment ID
7|JSSCP UAT NEW|Enrolment ID
8|Mobile creches|Enrolment ID

**Comment by vinayvenu** [comment]
@himeshr added to release card - https://github.com/avniproject/avni-client/issues/1021

**Comment by himeshr** [comment]
### Dev testing done on staging environment for :
1. Subject registration summary has GroupAffiliation msg (Phulwari org)
2. Enrolment to program has Enrolment ID auto generated based on GroupAffiliation (JSS SIngrauli org)

### Attached screen shots for the same:

<img width="751" alt="EnrolmentIdAutoGenerationBasedOnGroup" src="https://github.com/avniproject/avni-models/assets/72493481/00df8f92-537a-41a5-af5f-775b904cb230">
<img width="751" alt="SubjectRegistrationSummaryGroupAffiliationMsg" src="https://github.com/avniproject/avni-models/assets/72493481/59b88fa7-c7e8-4dc4-bca1-ea773823d03e">
