### ISSUE TITLE
Processing based on time zone

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-models#53]
### Steps:
- Login to maha@cd, prerelease env 
- and do School Monitoring encounters for 'ABC Vidhyalaya'
- All dates times are converted to/displayed in IST from UTC in the db - when we do console.log in a rule or in mobile app UI, it is the IST datetime that displays.
- In prod env, Cini - visit schedule rule for the above encounter type has 6 hours added thinking the UTC to IST conversion is not done at product level

### AC:
- Identify where the above conversion is made.

### Need:
The above is needed because as per the implementation team, the conversion doesn't happen. Identifying where we are doing the above, will help us to identify if any edge cases exist, that needs to be fixed.

## Old: Ignore
Have a configuration - of country somewhere

![Image](https://github.com/user-attachments/assets/66916ef2-fad6-4f6e-b1a3-5a0bd64f4a5e)

### Inputs:
- default report cards, VSR
- Region in Account
- search filter
- audit fields
- API? 
- which screen?
- account admin - not useful but used
- get the timezone from mobile app - is the timezone in mobile app reliable?
- CK sitting in US

**Comment by petmongrels** [comment]
https://gist.github.com/sachsk/e7a9e9b6e666aca4ffc99403a280d533

**Comment by petmongrels** [comment]
our dates are like "2024-03-23T06:08:45.000Z" in the offline db. Using Z in the timestamp means UTC. When we display the date using console.log we are shown the date in human friendly timezone converted format.

**Comment by mahalakshme** [comment]
@petmongrels where is the conversion happening? How does it know it needs to convert to IST?

**Comment by petmongrels** [comment]
The timezone comes from the JS runtime environment. It is just the display that is changed.
We can use sensors feature to test this out. Same date will be shown differently by changing the geolocation - https://www.youtube.com/watch?v=pIpN_AuV4AI
